const RAINBOW_GRADIENT = "linear-gradient(160deg, #FDEDEA 0%, #FDF3DD 30%, #FBFAE0 55%, #E9F6EA 75%, #E2F5F2 100%)";

const PRIVACY_SECTIONS = [
  {
    title: "What we collect",
    body: "When you create an account, we collect your email address and, optionally, a mobile number. For each child profile, we store a first name and the practice data generated by using the app — words practiced, scores, and progress over time. We do not collect a child's full legal name, address, or other identifying details unless a parent/guardian chooses to provide them."
  },
  {
    title: "Voice recordings",
    body: "When your child records a word, that audio is sent to our servers to generate feedback in real time. We process the recording to analyze pronunciation and then discard it — we do not retain a permanent copy of voice recordings."
  },
  {
    title: "Children's privacy",
    body: "Vaakify is designed to be set up and supervised by a parent or guardian. We do not knowingly collect personal information directly from a child without a parent or guardian first creating and controlling the account. If you believe a child has provided us information outside of this process, contact us using the details below and we'll remove it."
  },
  {
    title: "How we use your data",
    body: "We use account and practice data to run the core features of the app — tracking progress, tailoring practice to your child's needs, and enabling sign-in. We do not sell your data or your child's data to third parties, and we do not use it for advertising."
  },
  {
    title: "Third parties",
    body: "We use third-party infrastructure providers to host and run the app (for example, cloud hosting and speech-processing services). These providers process data on our behalf and are not permitted to use it for their own purposes."
  },
  {
    title: "Data retention & deletion",
    body: "Account and progress data is kept for as long as your account is active. You can request deletion of your account and associated data at any time through Settings, or by contacting us directly."
  },
  {
    title: "Your rights",
    body: "You can access, correct, or delete your account's data at any time. If you have questions about what we store, reach out — see Contact below."
  },
  {
    title: "Changes to this policy",
    body: "We may update this policy as the app evolves. We'll update the effective date below when we do."
  },
];

const TERMS_SECTIONS = [
  {
    title: "Acceptance of terms",
    body: "By using Vaakify, you agree to these terms. If you don't agree, please don't use the app."
  },
  {
    title: "What Vaakify is — and isn't",
    body: "Vaakify is a speech-practice tool designed to support pronunciation practice through interactive, phoneme-level feedback. It is not a medical device, and it does not diagnose, treat, or replace professional speech-language therapy or medical care. Always consult a licensed speech-language pathologist or medical professional for diagnosis or treatment decisions."
  },
  {
    title: "Who can use Vaakify",
    body: "Accounts must be created and managed by a parent or legal guardian on behalf of a child. By creating an account, you confirm you have the authority to do so and to consent to this app's use on your child's behalf."
  },
  {
    title: "Your account",
    body: "You're responsible for keeping your account credentials secure and for all activity under your account. Let us know right away if you believe your account has been compromised."
  },
  {
    title: "Free trial & subscriptions",
    body: "Vaakify may offer a free trial period followed by a paid subscription. Pricing and billing terms will be presented clearly before any charge. You can cancel at any time; see Plans & pricing for current details."
  },
  {
    title: "Acceptable use",
    body: "Please don't use Vaakify to upload harmful, abusive, or illegal content, attempt to disrupt the service, or use it in any way inconsistent with its purpose as a children's speech-practice tool."
  },
  {
    title: "Disclaimer & limitation of liability",
    body: "Vaakify is provided \"as is,\" without warranties of any kind. To the fullest extent permitted by law, we are not liable for indirect, incidental, or consequential damages arising from your use of the app."
  },
  {
    title: "Changes to these terms",
    body: "We may update these terms from time to time. Continued use of the app after changes means you accept the updated terms."
  },
  {
    title: "Governing law",
    body: "These terms are governed by the laws of [Your country/state]."
  },
];

export default function LegalPage({ type, onBack }) {
  const isPrivacy = type === "privacy";
  const sections = isPrivacy ? PRIVACY_SECTIONS : TERMS_SECTIONS;

  return (
    <div style={{ minHeight: "100vh", background: RAINBOW_GRADIENT, fontFamily: "Inter, sans-serif" }}>
      <div style={{ maxWidth: "760px", margin: "0 auto", padding: "clamp(24px, 6vw, 48px) clamp(18px, 5vw, 32px) 80px" }}>
        {onBack && (
          <button onClick={onBack} style={{
            background: "none", border: "none", color: "#3A2E2C", fontWeight: 700,
            fontSize: "0.85rem", cursor: "pointer", fontFamily: "Inter, sans-serif",
            marginBottom: "28px", display: "flex", alignItems: "center", gap: "6px", padding: 0,
          }}>
            ← Back
          </button>
        )}

        <h1 style={{
          fontFamily: "Nunito, sans-serif", fontWeight: 900, fontSize: "clamp(1.8rem, 6vw, 2.4rem)",
          color: "#2A211D", margin: "0 0 8px 0",
        }}>
          {isPrivacy ? "Privacy Policy" : "Terms of Service"}
        </h1>
        <p style={{ fontFamily: "Inter, sans-serif", fontSize: "0.85rem", color: "#9A7A6A", margin: "0 0 36px 0" }}>
          Effective date: [Month Day, Year] · Last updated: [Month Day, Year]
        </p>

        {sections.map((s) => (
          <div key={s.title} style={{ marginBottom: "28px" }}>
            <h2 style={{ fontFamily: "Nunito, sans-serif", fontWeight: 800, fontSize: "1.1rem", color: "#2A211D", margin: "0 0 8px 0" }}>
              {s.title}
            </h2>
            <p style={{ fontFamily: "Inter, sans-serif", fontSize: "0.92rem", color: "#5A4A42", lineHeight: 1.7, margin: 0 }}>
              {s.body}
            </p>
          </div>
        ))}

        <div style={{ marginTop: "40px", paddingTop: "24px", borderTop: "1.5px solid rgba(0,0,0,0.08)" }}>
          <h2 style={{ fontFamily: "Nunito, sans-serif", fontWeight: 800, fontSize: "1.1rem", color: "#2A211D", margin: "0 0 8px 0" }}>
            Contact
          </h2>
          <p style={{ fontFamily: "Inter, sans-serif", fontSize: "0.92rem", color: "#5A4A42", lineHeight: 1.7, margin: 0 }}>
            Questions about this {isPrivacy ? "policy" : "agreement"}? Reach us at [YOUR CONTACT EMAIL].
          </p>
        </div>
      </div>
    </div>
  );
}
